### PR TITLE
cc7-based ROOT image

### PR DESCRIPTION
**Pull request by lukasheinrich**
this builds ROOT on top of the officially maintained CERN flavor of Centos.

* provides Kerberos authentication out of the box
* adds XrootD-client

### CODE REVIEW

**Comment by lukasheinrich** [comment]
resolves #2

**Comment by lukasheinrich** [comment]
A test build with this Dockerfile is here:

```
docker pull lukasheinrich/rootproject-root-cc7:latest
```

which allows me to do

```
docker run --rm -it lukasheinrich/rootproject-root-cc7:latest bash
[root@26f2ba329ebb /]# kinit lheinric@CERN.CH
[root@26f2ba329ebb /]# root -b 
[root@26f2ba329ebb /]# root -b 
   ------------------------------------------------------------
  | Welcome to ROOT 6.15/01                http://root.cern.ch |
  |                               (c) 1995-2018, The ROOT Team |
  | Built for linuxx8664gcc                                    |
  | From heads/master@9999fb5, Aug 08 2018, 15:45:00           |
  | Try '.help', '.demo', '.license', '.credits', '.quit'/'.q' |
   ------------------------------------------------------------

root [0] TFile::Open("root://eosuser.cern.ch//eos/project/r/recast/atlas/ATLAS-CONF-2018-041/testdata/signal_evsel_inputs/mc16_13TeV.375893.MGPy8EG_A14N_GG_ttn1_2100_5000_1.deriv.DAOD_SUSY10.e6351_e5984_a875_r9364_r9315_p3387/DAOD_SUSY10.13001376._000001.pool.root.1")

Warning in <TClass::Init>: no dictionary for class xAOD::TruthMetaData_v1 is available
Warning in <TClass::Init>: no dictionary for class DataHeader_p5 is available
```

**Comment by cburgard** [comment]
I fully support this :-)

**Comment by amadio** [comment]
Thanks!

**Pull request merged**
