### PR TITLE
Prevents partial upgrades

### PR DESCRIPTION
**Pull request by kgizdov**
Fixes a previously introduced bug

### CODE REVIEW

**Comment by kgizdov** [comment]
@amadio no idea why it lists the old commits again - I've only changed a single line...

**Comment by amadio** [comment]
I think it's because I squashed on merge. Please rebase on current master and drop commits already applied.

**Comment by kgizdov** [comment]
@amadio fixed

**Comment by amadio** [comment]
Thanks, and sorry for the delay in merging.

**Pull request merged**
