### PR TITLE
Add README.md

### PR DESCRIPTION
**Pull request by eguiraud**
Copied from the root-ubuntu-16 README on Docker Hub.

### CODE REVIEW

**Comment by eguiraud** [comment]
> I think this should go to the website and we put just a link here

It's already up at https://hub.docker.com/r/rootproject/root. Here we can have it under version control, the version on the website can get lost easily (automatic builds can even overwrite it), so I'd keep it here too.

> Also I would like to have an explanation of how to find where which image

At the moment the README links to https://hub.docker.com/r/rootproject/root/tags . I think it's a good enough first step. We can add more text later :+1:

**Comment by eguiraud** [comment]
The real problem is telling people that images other than https://hub.docker.com/r/rootproject/root are not going to be updated and they should switch to one of the tags of that image.

**Comment by stwunsch** [comment]
Is it possible to push READMEs to the deprecated repos on dockerhub?

**Comment by eguiraud** [comment]
We can edit them directly, no need to use a docker plugin

**Comment by amadio** [comment]
The README could have a list of planned/supported tags. See the [busybox](https://hub.docker.com/_/busybox) README for example.

**Comment by eguiraud** [comment]
> The README could have a list of planned/supported tags. See the busybox and python READMEs for example.

That's now #19

**Pull request merged**
