### PR TITLE
Add Docker image for ArchLinux

### PR DESCRIPTION
**Pull request by kgizdov**
Tested and published on Docker Hub at [kgizdov:archlinux-root-extra](https://hub.docker.com/r/kgizdov/archlinux-root-extra/)

### CODE REVIEW

**Comment by amadio** [comment]
@kgizdov Hi. The image failed to build for me, at the boost step. Could you please review?

**Comment by kgizdov** [comment]
@amadio what is `the boost step`? Can you send me the error?

Also, Ubuntu, CentOS & Gentoo are ok, but Arch Linux is the actual named *trademark* that should be used ([policy](https://wiki.archlinux.org/index.php/DeveloperWiki:TrademarkPolicy)). I can change the folder name, but it will be incorrect according to naming. Also, `arch` means architecture a lot of the times.

**Comment by amadio** [comment]
```
Step 32/48 : RUN cd /tmp/pythia && makepkg -sri --asdeps --needed --noconfirm
 ---> Running in 0b793ec3eb53
==> Making package: pythia 8.2.35-5 (Wed Sep 26 13:11:58 2018)
==> Checking runtime dependencies...
==> Installing missing dependencies...
resolving dependencies...
looking for conflicting packages...

Packages (1) boost-1.68.0-1

Total Download Size:    12.13 MiB
Total Installed Size:  165.81 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
downloading boost-1.68.0-1-x86_64.pkg.tar.xz...
checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
checking available disk space...
:: Processing package changes...
installing boost...
error: could not extract /usr/include/boost/fusion/view/reverse_view.hpp (Can't create '/usr/include/boost/fusion/view/reverse_view.hpp')
error: could not extract /usr/include/boost/geometry.hpp (Can't create '/usr/include/boost/geometry.hpp')
error: could not extract /usr/include/boost/geometry/algorithms/clear.hpp (Can't create '/usr/include/boost/geometry/algorithms/clear.hpp')
...
```

**Comment by amadio** [comment]
> @amadio what is `the boost step`? Can you send me the error?
> 
> Also, Ubuntu, CentOS & Gentoo are ok, but Arch Linux is the actual named _trademark_ that should be used ([policy](https://wiki.archlinux.org/index.php/DeveloperWiki:TrademarkPolicy)). I can change the folder name, but it will be incorrect according to naming. Also, `arch` means architecture a lot of the times.

Well, AUR still stands for Arch User Repository, and the distro is commonly referred to as only Arch. I don't think that it's a problem to name the directory `arch` in this context. Also see the screenshot below from the main page of the Arch Wiki, where it's clearly referred to as just Arch ("...differences between Arch and other distributions").

screenshot

**Comment by kgizdov** [comment]
hmm, that is an error with the package manager not being able to install a package, so not a problem with the `Dockerfile` per say. Are you sure you have enough disk space? (`Docker` does not report correct free space inside a build). If all previous steps succeeded, there is no reason why this should fail - this step is equivalent. I am planning on reducing the size of docker (steps), but that would have to wait as I'm busy with other things for the rest of the week.

---

I am only pointing out the way it's meant to be done according to actual title, which is not the same for the OSes you mentioned.  `archlinux` is the correct way it should be, but I don't personally mind, I'll change it. (Wikis can be edited by anyone :wink:)

**Comment by amadio** [comment]
I'm building the image on a larger machine to check that it's not some system limitation, and so far it's working. I think that it will finish.

As for the name, it's the official wiki calling it Arch, I really don't see a difference with other distros. Everyone knows Arch, so let's just name it that. They call their Docker image `base/devel`, so it's not like we are doing any worse :wink:

**Comment by kgizdov** [comment]
try it now and see if it builds better

**Comment by amadio** [comment]
I tried the old image on a bigger machine and it worked. If you want to keep it as it was, I think it's fine.

**Comment by amadio** [comment]
@kgizdov Sure, I'll test again and then merge.

**Comment by kgizdov** [comment]
@amadio I've pushed a couple of fixes and now it should be reproducible to build it on any system.

**Comment by amadio** [comment]
Nice, thanks!

**Pull request merged**
