### PR TITLE
Fix pacman call

### PR DESCRIPTION
**Pull request by kgizdov**
`pacman` needs `--noconfirm`

### CODE REVIEW

**Comment by amadio** [comment]
No merge commits, please. Maybe adding the lines below to your `~/.gitconfig` will help:
```
[pull]
        ff = only
        rebase = merges
```
This will ensure that a `git pull` will automatically rebase rather than merge.

**Comment by kgizdov** [comment]
@amadio could you squash the commits instead?

**Comment by kgizdov** [comment]
@amadio squashed them for you

**Comment by amadio** [comment]
I can squash, but then you'll have the same problem next time, as the commit I will add is not a fast forward from what you have, and it also loses your signature. Now I can just merge it as is. Thanks!

**Pull request merged**
